name: Bit Lane Branch
on:
  workflow_dispatch:
    inputs:
      lane_name:
        description: "The name of the lane to sync from in the format: org.scope/lane"
        required: true
        default: ""
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      BIT_CONFIG_ACCESS_TOKEN: ${{ secrets.BIT_CONFIG_ACCESS_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Initialize Bit
        uses: bit-tasks/init@v3
        with:
          skip-install: "true"
      - name: Bit Lane Branch
        uses: bit-tasks/lane-branch@v1
        with:
          lane-name: ${{ github.event.inputs.lane_name }}